#!/bin/sh
#
# direct STDERR to STDOUT
exec 2>&1
cd /usr/local/nictool/ns/NAMESERVER
#
EXPORT_USER=nictool
export NT_EXPORT_KNOT_VERSION=2
#
# when this run file is executed, it will run the nt_export.pl script with the
# privileges of the EXPORT_USER. To export successfully, the enclosing
# directory likely needs write permission by the export user. If it doesn't,
# try this: chown -R nictool /usr/local/nictool/ns/NAMESERVER
#
# Choose from one of the three deployment models, using comments to
# activate only one exec entry.
#
######################################################
# For use with init, upstart, daemontools, or comparable.
######################################################
exec su -m $EXPORT_USER -c " ./nt_export.pl -nsid 34 -daemon -pfextra | logger -t nt_export_NAMESERVER"
#
# for daemontools, symlink this directory into the service directory.
# If svscan is running, the export will run almost immediately.
#   ln -s /usr/local/nictool/ns/NAMESERVER /var/service
#
######################################################
# For use with periodic triggers like cron and at
######################################################
#exec /usr/bin/perl ./nt_export.pl -nsid 34 -pfextra | logger -t nt_export_NAMESERVER
#
# this entry is suitable for addition to /etc/crontab
# */3    *    *    *    *    nictool /usr/local/nictool/ns/NAMESERVER/run
#
# this entry is suitable for addition to nictool's crontab:
# */3    *    *    *    *    /usr/local/nictool/ns/NAMESERVER/run
#
######################################################
# For interactive human use.
######################################################
# Note that the -force option is included, as you likely want to export
# regardless of DB changes since the last successful export.
#exec su -m $EXPORT_USER -c " ./nt_export.pl -nsid 34 -force -pfextra "

# return to whence we came
cd -
